name: flutter_ecommerce_project
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  auto_animated: ^3.0.1
  badges: ^2.0.2
  cached_network_image: ^3.2.0
  cloud_firestore: ^3.1.9
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  device_preview: ^0.7.5
  dropdown_search: ^3.0.1
  firebase_core: ^1.12.0
  firebase_messaging: ^11.2.7
  flutter:
    sdk: flutter
  flutter_local_notifications: ^9.5.3+1
  flutter_polyline_points: ^1.0.0
  fluttericon: ^2.0.0
  font_awesome_flutter: ^10.1.0
  geocoding: ^2.0.4
  geolocator: ^8.0.5
  get: ^4.6.1
  google_fonts: ^4.0.3
  google_maps_flutter: ^2.1.5
  google_sign_in: ^5.3.1
  grouped_list: ^4.2.0
  http: ^0.13.4
  image_picker: ^0.7.2+1
  image_pickers: ^2.0.0+2
  intl: ^0.17.0
  jiffy: ^5.0.0
  path: ^1.8.0
  qr_flutter: ^4.0.0
  responsive_builder: ^0.4.2
  scan: ^1.6.0
  shared_preferences: ^2.0.15
  show_up_animation: ^2.0.0
  sqflite: ^2.0.2
  url_launcher: ^6.1.2

dev_dependencies:

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
  # fonts:
  #   - family: Cairo
  #     fonts:
  #       - asset: assets/fonts/cairo_font.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
